openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Message Template API
    description: Endpoints for managing message templates.
paths:
  /mps/templates:
    post:
      tags:
        - Message Template API
      summary: Create a new message template
      description: Creates a new message template based on the provided request.
      operationId: createTamplateByName
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateRequest'
        required: true
      responses:
        '201':
          description: Template created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TemplateRequest'
        '400':
          description: Invalid input provided
          content:
            '*/*':
              example:
                error: Invalid input
    patch:
      tags:
        - Message Template API
      summary: Update an existing message template
      description: Updates an existing message template based on the provided request.
      operationId: updateTamplateByName
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateRequest'
        required: true
      responses:
        '200':
          description: Template updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TemplateRequest'
        '400':
          description: Invalid input provided
          content:
            '*/*':
              example:
                error: Invalid input
  /mps/templates/{name}:
    get:
      tags:
        - Message Template API
      summary: Get a message template by name
      description: Retrieves a message template by its name.
      operationId: getTamplateByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Template retrieved successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TemplateRequest'
        '404':
          description: Template not found
          content:
            '*/*':
              example:
                error: Template not found
components:
  schemas:
    TemplateRequest:
      required:
        - body
        - name
        - subject
      type: object
      properties:
        name:
          type: string
        subject:
          type: string
        body:
          type: string
      description: TemplateRequest model for API request
